FROM cimg/python:3.9

WORKDIR /home/circleci

ADD --chown=circleci:circleci ./pyproject.toml ./tox.ini ./poetry.lock ./project/

WORKDIR /home/circleci/project

ARG CIRCLECI

# Need to turn build args to env vars so that entrypoint script can see them.
ENV CIRCLECI=${CIRCLECI}

ENV NEO4J_DB_URL=neo4j
ENV DATABASE_HOST=postgres_db

RUN sudo `which pip` install --upgrade pip tox poetry
RUN tox -e install-deps

ADD --chown=circleci:circleci . .


ENTRYPOINT /home/circleci/project/entrypoint.sh
