"""Initial migration.

Revision ID: 80db87e665d5
Revises: 
Create Date: 2022-05-31 10:15:26.485617

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "80db87e665d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "diagnosis",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("sct_code", sa.String(), nullable=True),
        sa.Column("diagnosis_other", sa.String(), nullable=True),
        sa.Column("diagnosed", sa.Date(), nullable=True),
        sa.Column("resolved", sa.Date(), nullable=True),
        sa.Column("presented", sa.Date(), nullable=True),
        sa.Column("episode", sa.Integer(), nullable=True),
        sa.Column("diagnosis_tool", sa.JSON(), nullable=True),
        sa.Column("diagnosis_tool_other", sa.String(), nullable=True),
        sa.Column("risk_factors", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "history",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("parity", sa.Integer(), nullable=True),
        sa.Column("gravidity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "note",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("clinician_uuid", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "patient",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("patient_type", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("dod", sa.Date(), nullable=True),
        sa.Column("nhs_number", sa.String(), nullable=True),
        sa.Column("hospital_number", sa.String(), nullable=True),
        sa.Column("allowed_to_text", sa.Boolean(), nullable=True),
        sa.Column("allowed_to_email", sa.Boolean(), nullable=True),
        sa.Column("email_address", sa.String(), nullable=True),
        sa.Column("ethnicity", sa.String(), nullable=True),
        sa.Column("ethnicity_other", sa.String(), nullable=True),
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("height_in_mm", sa.Integer(), nullable=True),
        sa.Column("weight_in_g", sa.Integer(), nullable=True),
        sa.Column("highest_education_level", sa.String(), nullable=True),
        sa.Column("highest_education_level_other", sa.String(), nullable=True),
        sa.Column("accessibility_considerations", sa.JSON(), nullable=False),
        sa.Column("accessibility_considerations_other", sa.String(), nullable=True),
        sa.Column("other_notes", sa.String(), nullable=True),
        sa.Column("locations", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "bookmarked_at_locations", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("has_been_bookmarked", sa.Boolean(), nullable=True),
        sa.Column("record_id", sa.String(), nullable=True),
        sa.Column("parent_patient_id", sa.String(), nullable=True),
        sa.Column("fhir_resource_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_patient_id"],
            ["patient.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        "hospital_number_unique_index",
        "patient",
        ["hospital_number"],
        unique=True,
        postgresql_where=sa.text(
            "hospital_number IS NOT NULL AND patient_type = 'send'"
        ),
    )
    op.create_index(
        "nhs_number_unique_index",
        "patient",
        ["nhs_number"],
        unique=True,
        postgresql_where=sa.text("nhs_number IS NOT NULL AND patient_type = 'send'"),
    )
    op.create_table(
        "pregnancy",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("estimated_delivery_date", sa.Date(), nullable=True),
        sa.Column("planned_delivery_place", sa.String(), nullable=True),
        sa.Column("length_of_postnatal_stay_in_days", sa.Integer(), nullable=True),
        sa.Column("colostrum_harvesting", sa.Boolean(), nullable=True),
        sa.Column("expected_number_of_babies", sa.Integer(), nullable=True),
        sa.Column("pregnancy_complications", sa.JSON(), nullable=True),
        sa.Column("induced", sa.Boolean(), nullable=True),
        sa.Column("height_at_booking_in_mm", sa.Integer(), nullable=True),
        sa.Column("weight_at_booking_in_g", sa.Integer(), nullable=True),
        sa.Column("weight_at_diagnosis_in_g", sa.Integer(), nullable=True),
        sa.Column("weight_at_36_weeks_in_g", sa.Integer(), nullable=True),
        sa.Column("delivery_place", sa.String(), nullable=True),
        sa.Column("delivery_place_other", sa.String(), nullable=True),
        sa.Column("first_medication_taken", sa.String(), nullable=True),
        sa.Column("first_medication_taken_recorded", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "visit",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("diagnoses", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("visit_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("clinician_uuid", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "delivery",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("pregnancy_id", sa.String(), nullable=False),
        sa.Column("birth_outcome", sa.String(), nullable=True),
        sa.Column("outcome_for_baby", sa.String(), nullable=True),
        sa.Column("neonatal_complications", sa.JSON(), nullable=True),
        sa.Column("neonatal_complications_other", sa.String(), nullable=True),
        sa.Column("admitted_to_special_baby_care_unit", sa.Boolean(), nullable=True),
        sa.Column("birth_weight_in_grams", sa.Integer(), nullable=True),
        sa.Column("length_of_postnatal_stay_for_baby", sa.Integer(), nullable=True),
        sa.Column("apgar_1_minute", sa.Integer(), nullable=True),
        sa.Column("apgar_5_minute", sa.Integer(), nullable=True),
        sa.Column("feeding_method", sa.String(), nullable=True),
        sa.Column("date_of_termination", sa.Date(), nullable=True),
        sa.Column("patient_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["pregnancy_id"],
            ["pregnancy.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_delivery_patient_id"), "delivery", ["patient_id"], unique=False
    )
    op.create_table(
        "drayson_health_product",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("opened_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("closed_reason", sa.String(), nullable=True),
        sa.Column("closed_reason_other", sa.String(), nullable=True),
        sa.Column("accessibility_discussed", sa.Boolean(), nullable=False),
        sa.Column("accessibility_discussed_with", sa.String(), nullable=True),
        sa.Column("accessibility_discussed_date", sa.Date(), nullable=True),
        sa.Column("monitored_by_clinician", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "management_plan",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_id", sa.String(), nullable=False),
        sa.Column("plan_history", sa.JSON(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("sct_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnosis.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "observable_entity",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_id", sa.String(), nullable=True),
        sa.Column("sct_code", sa.String(), nullable=True),
        sa.Column("date_observed", sa.Date(), nullable=True),
        sa.Column("value_as_string", sa.String(), nullable=True),
        sa.Column("metadata_", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnosis.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "personal_address",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("address_line_1", sa.String(), nullable=True),
        sa.Column("address_line_2", sa.String(), nullable=True),
        sa.Column("address_line_3", sa.String(), nullable=True),
        sa.Column("address_line_4", sa.String(), nullable=True),
        sa.Column("locality", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("lived_from", sa.Date(), nullable=True),
        sa.Column("lived_until", sa.Date(), nullable=True),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "readings_plan",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("diagnosis_id", sa.String(), nullable=False),
        sa.Column("days_per_week_to_take_readings", sa.Integer(), nullable=True),
        sa.Column("readings_per_day", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("sct_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["diagnosis_id"],
            ["diagnosis.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "terms_agreement",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column(
            "accepted_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("tou_version", sa.Integer(), nullable=True),
        sa.Column(
            "tou_accepted_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("patient_notice_version", sa.Integer(), nullable=True),
        sa.Column(
            "patient_notice_accepted_timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "dose",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("management_plan_id", sa.String(), nullable=True),
        sa.Column("medication_id", sa.String(), nullable=True),
        sa.Column("dose_amount", sa.Float(), nullable=True),
        sa.Column("routine_sct_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["management_plan_id"],
            ["management_plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "drayson_health_product_change",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("drayson_health_product_id", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["drayson_health_product_id"],
            ["drayson_health_product.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "non_medication_action",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("management_plan_id", sa.String(), nullable=False),
        sa.Column("action_sct_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["management_plan_id"],
            ["management_plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "readings_plan_change",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("readings_plan_id", sa.String(), nullable=False),
        sa.Column("days_per_week_to_take_readings", sa.Integer(), nullable=True),
        sa.Column("readings_per_day", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["readings_plan_id"],
            ["readings_plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "dose_change",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("dose_id", sa.String(), nullable=False),
        sa.Column("medication_id", sa.String(), nullable=True),
        sa.Column("dose_amount", sa.Float(), nullable=True),
        sa.Column("routine_sct_code", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dose_id"],
            ["dose.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "dose_history",
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("created_by_", sa.String(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("modified_by_", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("management_plan_id", sa.String(), nullable=False),
        sa.Column("dose_id", sa.String(), nullable=False),
        sa.Column("clinician_uuid", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dose_id"],
            ["dose.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["management_plan_id"],
            ["management_plan.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dose_history")
    op.drop_table("dose_change")
    op.drop_table("readings_plan_change")
    op.drop_table("non_medication_action")
    op.drop_table("drayson_health_product_change")
    op.drop_table("dose")
    op.drop_table("terms_agreement")
    op.drop_table("readings_plan")
    op.drop_table("personal_address")
    op.drop_table("observable_entity")
    op.drop_table("management_plan")
    op.drop_table("drayson_health_product")
    op.drop_index(op.f("ix_delivery_patient_id"), table_name="delivery")
    op.drop_table("delivery")
    op.drop_table("visit")
    op.drop_table("pregnancy")
    op.drop_index(
        "nhs_number_unique_index",
        table_name="patient",
        postgresql_where=sa.text("nhs_number IS NOT NULL AND patient_type = 'send'"),
    )
    op.drop_index(
        "hospital_number_unique_index",
        table_name="patient",
        postgresql_where=sa.text(
            "hospital_number IS NOT NULL AND patient_type = 'send'"
        ),
    )
    op.drop_table("patient")
    op.drop_table("note")
    op.drop_table("history")
    op.drop_table("diagnosis")
    op.drop_table("record")
    # ### end Alembic commands ###
