"""cascade on foreign keys

Revision ID: 9b57875239bb
Revises: 64b3f3dfef11
Create Date: 2022-06-08 15:38:30.369480

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b57875239bb"
down_revision = "64b3f3dfef11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("delivery_pregnancy_id_fkey", "delivery", type_="foreignkey")
    op.create_foreign_key(
        "delivery_pregnancy_id_fkey",
        "delivery",
        "pregnancy",
        ["pregnancy_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("diagnosis_record_id_fkey", "diagnosis", type_="foreignkey")
    op.create_foreign_key(
        "diagnosis_record_id_fkey",
        "diagnosis",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("dose_management_plan_id_fkey", "dose", type_="foreignkey")
    op.create_foreign_key(
        "dose_management_plan_id_fkey",
        "dose",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
        ondelete="SET NULL",
    )
    op.drop_constraint("dose_change_dose_id_fkey", "dose_change", type_="foreignkey")
    op.create_foreign_key(
        "dose_change_dose_id_fkey",
        "dose_change",
        "dose",
        ["dose_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("dose_history_dose_id_fkey", "dose_history", type_="foreignkey")
    op.drop_constraint(
        "dose_history_management_plan_id_fkey", "dose_history", type_="foreignkey"
    )
    op.create_foreign_key(
        "dose_history_dose_id_fkey",
        "dose_history",
        "dose",
        ["dose_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "dose_history_management_plan_id_fkey",
        "dose_history",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "drayson_health_product_patient_id_fkey",
        "drayson_health_product",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "drayson_health_product_patient_id_fkey",
        "drayson_health_product",
        "patient",
        ["patient_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "drayson_health_product_change_drayson_health_product_id_fkey",
        "drayson_health_product_change",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "drayson_health_product_change_drayson_health_product_id_fkey",
        "drayson_health_product_change",
        "drayson_health_product",
        ["drayson_health_product_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("history_record_id_fkey", "history", type_="foreignkey")
    op.create_foreign_key(
        "history_record_id_fkey",
        "history",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "management_plan_diagnosis_id_fkey", "management_plan", type_="foreignkey"
    )
    op.create_foreign_key(
        "management_plan_diagnosis_id_fkey",
        "management_plan",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "non_medication_action_management_plan_id_fkey",
        "non_medication_action",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "non_medication_action_management_plan_id_fkey",
        "non_medication_action",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("note_record_id_fkey", "note", type_="foreignkey")
    op.create_foreign_key(
        "note_record_id_fkey",
        "note",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "observable_entity_diagnosis_id_fkey", "observable_entity", type_="foreignkey"
    )
    op.create_foreign_key(
        "observable_entity_diagnosis_id_fkey",
        "observable_entity",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("patient_record_id_fkey", "patient", type_="foreignkey")
    op.drop_constraint("patient_parent_patient_id_fkey", "patient", type_="foreignkey")
    op.create_foreign_key(
        "patient_record_id_fkey",
        "patient",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "patient_parent_patient_id_fkey",
        "patient",
        "patient",
        ["parent_patient_id"],
        ["uuid"],
        ondelete="SET NULL",
    )
    op.drop_constraint(
        "personal_address_patient_id_fkey", "personal_address", type_="foreignkey"
    )
    op.create_foreign_key(
        "personal_address_patient_id_fkey",
        "personal_address",
        "patient",
        ["patient_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("pregnancy_record_id_fkey", "pregnancy", type_="foreignkey")
    op.create_foreign_key(
        "pregnancy_record_id_fkey",
        "pregnancy",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "readings_plan_diagnosis_id_fkey", "readings_plan", type_="foreignkey"
    )
    op.create_foreign_key(
        "readings_plan_diagnosis_id_fkey",
        "readings_plan",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "readings_plan_change_readings_plan_id_fkey",
        "readings_plan_change",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "readings_plan_change_readings_plan_id_fkey",
        "readings_plan_change",
        "readings_plan",
        ["readings_plan_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "terms_agreement_patient_id_fkey", "terms_agreement", type_="foreignkey"
    )
    op.create_foreign_key(
        "terms_agreement_patient_id_fkey",
        "terms_agreement",
        "patient",
        ["patient_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    op.drop_constraint("visit_record_id_fkey", "visit", type_="foreignkey")
    op.create_foreign_key(
        "visit_record_id_fkey",
        "visit",
        "record",
        ["record_id"],
        ["uuid"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("visit_record_id_fkey", "visit", type_="foreignkey")
    op.create_foreign_key(
        "visit_record_id_fkey", "visit", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint(
        "terms_agreement_patient_id_fkey", "terms_agreement", type_="foreignkey"
    )
    op.create_foreign_key(
        "terms_agreement_patient_id_fkey",
        "terms_agreement",
        "patient",
        ["patient_id"],
        ["uuid"],
    )
    op.drop_constraint(
        "readings_plan_change_readings_plan_id_fkey",
        "readings_plan_change",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "readings_plan_change_readings_plan_id_fkey",
        "readings_plan_change",
        "readings_plan",
        ["readings_plan_id"],
        ["uuid"],
    )
    op.drop_constraint(
        "readings_plan_diagnosis_id_fkey", "readings_plan", type_="foreignkey"
    )
    op.create_foreign_key(
        "readings_plan_diagnosis_id_fkey",
        "readings_plan",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
    )
    op.drop_constraint("pregnancy_record_id_fkey", "pregnancy", type_="foreignkey")
    op.create_foreign_key(
        "pregnancy_record_id_fkey", "pregnancy", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint(
        "personal_address_patient_id_fkey", "personal_address", type_="foreignkey"
    )
    op.create_foreign_key(
        "personal_address_patient_id_fkey",
        "personal_address",
        "patient",
        ["patient_id"],
        ["uuid"],
    )
    op.drop_constraint("patient_parent_patient_id_fkey", "patient", type_="foreignkey")
    op.drop_constraint("patient_record_id_fkey", "patient", type_="foreignkey")
    op.create_foreign_key(
        "patient_parent_patient_id_fkey",
        "patient",
        "patient",
        ["parent_patient_id"],
        ["uuid"],
    )
    op.create_foreign_key(
        "patient_record_id_fkey", "patient", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint(
        "observable_entity_diagnosis_id_fkey", "observable_entity", type_="foreignkey"
    )
    op.create_foreign_key(
        "observable_entity_diagnosis_id_fkey",
        "observable_entity",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
    )
    op.drop_constraint("note_record_id_fkey", "note", type_="foreignkey")
    op.create_foreign_key(
        "note_record_id_fkey", "note", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint(
        "non_medication_action_management_plan_id_fkey",
        "non_medication_action",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "non_medication_action_management_plan_id_fkey",
        "non_medication_action",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
    )
    op.drop_constraint(
        "management_plan_diagnosis_id_fkey", "management_plan", type_="foreignkey"
    )
    op.create_foreign_key(
        "management_plan_diagnosis_id_fkey",
        "management_plan",
        "diagnosis",
        ["diagnosis_id"],
        ["uuid"],
    )
    op.drop_constraint("history_record_id_fkey", "history", type_="foreignkey")
    op.create_foreign_key(
        "history_record_id_fkey", "history", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint(
        "drayson_health_product_change_drayson_health_product_id_fkey",
        "drayson_health_product_change",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "drayson_health_product_change_drayson_health_product_id_fkey",
        "drayson_health_product_change",
        "drayson_health_product",
        ["drayson_health_product_id"],
        ["uuid"],
    )
    op.drop_constraint(
        "drayson_health_product_patient_id_fkey",
        "drayson_health_product",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "drayson_health_product_patient_id_fkey",
        "drayson_health_product",
        "patient",
        ["patient_id"],
        ["uuid"],
    )
    op.drop_constraint(
        "dose_history_management_plan_id_fkey", "dose_history", type_="foreignkey"
    )
    op.drop_constraint("dose_history_dose_id_fkey", "dose_history", type_="foreignkey")
    op.create_foreign_key(
        "dose_history_management_plan_id_fkey",
        "dose_history",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
    )
    op.create_foreign_key(
        "dose_history_dose_id_fkey", "dose_history", "dose", ["dose_id"], ["uuid"]
    )
    op.drop_constraint("dose_change_dose_id_fkey", "dose_change", type_="foreignkey")
    op.create_foreign_key(
        "dose_change_dose_id_fkey", "dose_change", "dose", ["dose_id"], ["uuid"]
    )
    op.drop_constraint("dose_management_plan_id_fkey", "dose", type_="foreignkey")
    op.create_foreign_key(
        "dose_management_plan_id_fkey",
        "dose",
        "management_plan",
        ["management_plan_id"],
        ["uuid"],
    )
    op.drop_constraint("diagnosis_record_id_fkey", "diagnosis", type_="foreignkey")
    op.create_foreign_key(
        "diagnosis_record_id_fkey", "diagnosis", "record", ["record_id"], ["uuid"]
    )
    op.drop_constraint("delivery_pregnancy_id_fkey", "delivery", type_="foreignkey")
    op.create_foreign_key(
        "delivery_pregnancy_id_fkey",
        "delivery",
        "pregnancy",
        ["pregnancy_id"],
        ["uuid"],
    )
    # ### end Alembic commands ###
